Repository ROCm/hipBLAS, pull requests merged in 2023-12, with the labels that each got.

#741 Allow debug builds in jenkins
  .jenkins/common.groovy
  clients/benchmarks/CMakeLists.txt
  clients/gtest/CMakeLists.txt
  clients/samples/CMakeLists.txt
  deps/external-gtest.cmake
  library/src/CMakeLists.txt
Labels: noSolver, debug

#748 Include 64-bit fortran module when building without rocsolver
  clients/include/hipblas_fortran_no_solver_module.f90
Labels: noSolver

#752 Adding 64-bit axpy
  clients/common/hipblas_template_specialization.cpp
  clients/gtest/blas1/axpy_gtest.yaml
  clients/include/blas1/testing_axpy.hpp
  clients/include/blas1/testing_axpy_batched.hpp
  clients/include/blas1/testing_axpy_strided_batched.hpp
  clients/include/hipblas.hpp
  clients/include/hipblas_fortran.h.in
  clients/include/hipblas_fortran.hpp
  clients/include/hipblas_fortran_blas_64.f90
  clients/include/hipblas_no_fortran.hpp
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/hipblas_module.f90
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#749 Adding gemvBatched and gemvStridedBatched with cuda backend
  clients/gtest/blas2/gemv_gtest.cpp
  clients/gtest/blas2/gemv_gtest.yaml
  clients/gtest/hipblas_test.cpp
  clients/include/blas2/testing_gemv.hpp
  clients/include/blas2/testing_gemv_batched.hpp
  clients/include/blas2/testing_gemv_strided_batched.hpp
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#755 Apply Documentation Standardization for ReadtheDocs
  .github/dependabot.yml
  .gitignore
  .readthedocs.yaml
  README.md
  docs/.sphinx/requirements.in
  docs/conf.py
  docs/doxygen/Doxyfile
  docs/license.rst
  docs/sphinx/_toc.yml.in
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: ci:docs-only
