Repository ROCm/hipBLAS, pull requests merged in 2024-04, with the labels that each got.

#827 update to current and fixed vcpkg version
  rdeps.py
Labels: noCI

#837 install -dev packages for rocblas and rocsolver
  install.sh
Labels: dependencies

#843 Update changelog.md for ROCm 6.2
  CHANGELOG.md
Labels: noCI

#842 Fix hipcc build for C example
  clients/samples/CMakeLists.txt
Labels: hipcc

#795 Re-enable static library job in CI
  .jenkins/static.groovy
  rmake.py
Labels: noSolver, ci:static-libraries

#850 docs: fix broken contributing link
  docs/index.rst
Labels: noCI, ci:docs-only
