Repository ROCm/hipBLAS, pull requests merged in 2024-01, with the labels that each got.

#756 Dot 64-bit interface
  clients/common/hipblas_template_specialization.cpp
  clients/gtest/blas1/dot_gtest.yaml
  clients/include/blas1/testing_asum.hpp
  clients/include/blas1/testing_dot.hpp
  clients/include/blas1/testing_dot_batched.hpp
  clients/include/blas1/testing_dot_strided_batched.hpp
  clients/include/hipblas.hpp
  clients/include/hipblas_fortran.h.in
  clients/include/hipblas_fortran.hpp
  clients/include/hipblas_fortran_blas_64.f90
  clients/include/hipblas_no_fortran.hpp
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/hipblas_module.f90
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#757 nrm2 64-bit interface
  clients/common/hipblas_template_specialization.cpp
  clients/gtest/blas1/nrm2_gtest.yaml
  clients/include/blas1/testing_nrm2.hpp
  clients/include/blas1/testing_nrm2_batched.hpp
  clients/include/blas1/testing_nrm2_strided_batched.hpp
  clients/include/hipblas.hpp
  clients/include/hipblas_fortran.h.in
  clients/include/hipblas_fortran.hpp
  clients/include/hipblas_fortran_blas_64.f90
  clients/include/hipblas_no_fortran.hpp
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/hipblas_module.f90
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#758 iamax and iamin 64-bit interface
  CMakeLists.txt
  clients/common/blis_interface.cpp
  clients/common/hipblas_template_specialization.cpp
  clients/common/near.cpp
  clients/common/norm.cpp
  clients/common/unit.cpp
  clients/gtest/blas1/iamaxmin_gtest.yaml
  clients/include/blas1/hipblas_iamax_iamin_ref.hpp
  clients/include/blas1/testing_asum_batched.hpp
  clients/include/blas1/testing_asum_strided_batched.hpp
  clients/include/blas1/testing_iamax_iamin.hpp
  clients/include/blas1/testing_iamax_iamin_batched.hpp
  clients/include/blas1/testing_iamax_iamin_strided_batched.hpp
  clients/include/blas2/testing_tbsv.hpp
  clients/include/blas2/testing_tbsv_batched.hpp
  clients/include/blas2/testing_tbsv_strided_batched.hpp
  clients/include/blas2/testing_tpsv.hpp
  clients/include/blas2/testing_tpsv_batched.hpp
  clients/include/blas2/testing_tpsv_strided_batched.hpp
  clients/include/blas2/testing_trsv.hpp
  clients/include/blas2/testing_trsv_batched.hpp
  clients/include/blas2/testing_trsv_strided_batched.hpp
  clients/include/blas3/testing_trsm.hpp
  clients/include/blas3/testing_trsm_batched.hpp
  clients/include/blas3/testing_trsm_strided_batched.hpp
  clients/include/blas_ex/testing_trsm_batched_ex.hpp
  clients/include/blas_ex/testing_trsm_ex.hpp
  clients/include/blas_ex/testing_trsm_strided_batched_ex.hpp
  clients/include/cblas_interface.h
  clients/include/d_vector.hpp
  clients/include/device_batch_vector.hpp
  clients/include/hipblas.hpp
  clients/include/hipblas_fortran.h.in
  clients/include/hipblas_fortran.hpp
  clients/include/hipblas_fortran_blas_64.f90
  clients/include/hipblas_no_fortran.hpp
  clients/include/hipblas_test.hpp
  clients/include/hipblas_vector.hpp
  clients/include/host_batch_vector.hpp
  clients/include/lapack_utilities.hpp
  clients/include/near.h
  clients/include/norm.h
  clients/include/testing_common.hpp
  clients/include/type_utils.h
  install.sh
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/hipblas_module.f90
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#762 Scal and swap 64-bit interface
  clients/common/hipblas_template_specialization.cpp
  clients/gtest/blas1/scal_gtest.yaml
  clients/gtest/blas1/swap_gtest.yaml
  clients/include/blas1/testing_scal.hpp
  clients/include/blas1/testing_scal_batched.hpp
  clients/include/blas1/testing_scal_strided_batched.hpp
  clients/include/blas1/testing_swap.hpp
  clients/include/blas1/testing_swap_batched.hpp
  clients/include/blas1/testing_swap_strided_batched.hpp
  clients/include/hipblas.hpp
  clients/include/hipblas_fortran.h.in
  clients/include/hipblas_fortran.hpp
  clients/include/hipblas_fortran_blas_64.f90
  clients/include/hipblas_no_fortran.hpp
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/hipblas_module.f90
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#764 changelog edits
  CHANGELOG.md
Labels: ci:docs-only

#760 Rot* 64-bit interface
  clients/common/hipblas_template_specialization.cpp
  clients/gtest/blas1/rot_gtest.yaml
  clients/include/blas1/testing_rot.hpp
  clients/include/blas1/testing_rot_batched.hpp
  clients/include/blas1/testing_rot_strided_batched.hpp
  clients/include/blas1/testing_rotg.hpp
  clients/include/blas1/testing_rotg_batched.hpp
  clients/include/blas1/testing_rotg_strided_batched.hpp
  clients/include/blas1/testing_rotm.hpp
  clients/include/blas1/testing_rotm_batched.hpp
  clients/include/blas1/testing_rotm_strided_batched.hpp
  clients/include/blas1/testing_rotmg.hpp
  clients/include/blas1/testing_rotmg_batched.hpp
  clients/include/blas1/testing_rotmg_strided_batched.hpp
  clients/include/hipblas.hpp
  clients/include/hipblas_fortran.h.in
  clients/include/hipblas_fortran.hpp
  clients/include/hipblas_fortran_blas_64.f90
  clients/include/hipblas_no_fortran.hpp
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/hipblas_module.f90
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#767 adds client license for lapack utils code
  LICENSE.md
  docs/install.rst
Labels: ci:docs-only

#771 Change API from *_64_v2 to *_v2_64
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#772 Add hipblasGetMathMode and hipblasSetMathMode
  clients/gtest/auxil/set_get_mode_gtest.cpp
  clients/gtest/auxil/set_get_mode_gtest.yaml
  clients/include/auxil/testing_set_get_math_mode.hpp
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#770 Add documentation for 64-bit interface
  docs/functions.rst
  library/include/hipblas.h
Labels: ci:docs-only

#776 Add hipblasComputeType_t documentation
  docs/functions.rst
  library/include/hipblas.h
Labels: ci:docs-only

#775 Default option LINK_BLIS to use ILP64 reference on linux
  deps/CMakeLists.txt
Labels: noSolver

#780 Adding documentation regarding complex type deprecations
  docs/functions.rst
Labels: ci:docs-only

#779 doc_reorg for diataxis
  docs/clients.rst
  docs/contributing.rst
  docs/deprecation.rst
  docs/functions.rst
  docs/index.rst
  docs/install.rst
  docs/orga.rst
  docs/sphinx/_toc.yml.in
Labels: ci:docs-only

#778 Add codeowners for documentation
  .github/CODEOWNERS
Labels: noCI
