Repository ROCm/hipBLAS, pull requests merged in 2024-03, with the labels that each got.

#805 Spr and spr2 64-bit interface
  clients/common/hipblas_template_specialization.cpp
  clients/gtest/blas2/spr2_gtest.yaml
  clients/gtest/blas2/spr_gtest.yaml
  clients/include/blas2/testing_spr.hpp
  clients/include/blas2/testing_spr2.hpp
  clients/include/blas2/testing_spr2_batched.hpp
  clients/include/blas2/testing_spr2_strided_batched.hpp
  clients/include/blas2/testing_spr_batched.hpp
  clients/include/blas2/testing_spr_strided_batched.hpp
  clients/include/hipblas.hpp
  clients/include/hipblas_fortran.h.in
  clients/include/hipblas_fortran.hpp
  clients/include/hipblas_fortran_blas_64.f90
  clients/include/hipblas_no_fortran.hpp
  docs/functions.rst
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/hipblas_module.f90
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#802 update TOC to match rocDecode
  docs/index.rst
  docs/sphinx/_toc.yml.in
Labels: ci:docs-only

#812 Update index.rst
  docs/index.rst
Labels: ci:docs-only

#810 symv, syr, syr2 64-bit interface
  clients/common/hipblas_template_specialization.cpp
  clients/common/utility.cpp
  clients/gtest/blas2/symv_gtest.yaml
  clients/gtest/blas2/syr2_gtest.yaml
  clients/gtest/blas2/syr_gtest.yaml
  clients/include/blas2/testing_symv.hpp
  clients/include/blas2/testing_symv_batched.hpp
  clients/include/blas2/testing_symv_strided_batched.hpp
  clients/include/blas2/testing_syr.hpp
  clients/include/blas2/testing_syr2.hpp
  clients/include/blas2/testing_syr2_batched.hpp
  clients/include/blas2/testing_syr2_strided_batched.hpp
  clients/include/blas2/testing_syr_batched.hpp
  clients/include/blas2/testing_syr_strided_batched.hpp
  clients/include/hipblas.hpp
  clients/include/hipblas_fortran.h.in
  clients/include/hipblas_fortran.hpp
  clients/include/hipblas_fortran_blas_64.f90
  clients/include/hipblas_no_fortran.hpp
  clients/include/utility.h
  docs/functions.rst
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/hipblas_module.f90
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#800 Update links
  docs/clients.rst
Labels: ci:docs-only

#811 tbsv tpsv trsv ILP64
  clients/common/hipblas_template_specialization.cpp
  clients/gtest/blas2/tbsv_gtest.yaml
  clients/gtest/blas2/tpsv_gtest.yaml
  clients/gtest/blas2/trsv_gtest.yaml
  clients/include/blas2/testing_tbsv.hpp
  clients/include/blas2/testing_tbsv_batched.hpp
  clients/include/blas2/testing_tbsv_strided_batched.hpp
  clients/include/blas2/testing_tpsv.hpp
  clients/include/blas2/testing_tpsv_batched.hpp
  clients/include/blas2/testing_tpsv_strided_batched.hpp
  clients/include/blas2/testing_trsv.hpp
  clients/include/blas2/testing_trsv_batched.hpp
  clients/include/blas2/testing_trsv_strided_batched.hpp
  clients/include/hipblas.hpp
  clients/include/hipblas_fortran.h.in
  clients/include/hipblas_fortran.hpp
  clients/include/hipblas_fortran_blas_64.f90
  clients/include/hipblas_no_fortran.hpp
  docs/functions.rst
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/hipblas_module.f90
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#815 gbmv, gemv, ger ILP64
  clients/common/hipblas_template_specialization.cpp
  clients/gtest/blas2/gbmv_gtest.yaml
  clients/gtest/blas2/gemv_gtest.yaml
  clients/gtest/blas2/ger_gtest.yaml
  clients/include/blas2/testing_gbmv.hpp
  clients/include/blas2/testing_gbmv_batched.hpp
  clients/include/blas2/testing_gbmv_strided_batched.hpp
  clients/include/blas2/testing_gemv.hpp
  clients/include/blas2/testing_gemv_batched.hpp
  clients/include/blas2/testing_gemv_strided_batched.hpp
  clients/include/blas2/testing_ger.hpp
  clients/include/blas2/testing_ger_batched.hpp
  clients/include/blas2/testing_ger_strided_batched.hpp
  clients/include/hipblas.hpp
  clients/include/hipblas_fortran.h.in
  clients/include/hipblas_fortran.hpp
  clients/include/hipblas_fortran_blas_64.f90
  clients/include/hipblas_no_fortran.hpp
  docs/functions.rst
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/hipblas_module.f90
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#818 64-bit interface for blas1 _ex functions
  clients/gtest/blas_ex/axpy_ex_gtest.yaml
  clients/gtest/blas_ex/dot_ex_gtest.yaml
  clients/gtest/blas_ex/nrm2_ex_gtest.yaml
  clients/gtest/blas_ex/rot_ex_gtest.yaml
  clients/gtest/blas_ex/scal_ex_gtest.yaml
  clients/gtest/hipblas_test.cpp
  clients/include/blas_ex/testing_axpy_batched_ex.hpp
  clients/include/blas_ex/testing_axpy_ex.hpp
  clients/include/blas_ex/testing_axpy_strided_batched_ex.hpp
  clients/include/blas_ex/testing_dot_batched_ex.hpp
  clients/include/blas_ex/testing_dot_ex.hpp
  clients/include/blas_ex/testing_dot_strided_batched_ex.hpp
  clients/include/blas_ex/testing_nrm2_batched_ex.hpp
  clients/include/blas_ex/testing_nrm2_ex.hpp
  clients/include/blas_ex/testing_nrm2_strided_batched_ex.hpp
  clients/include/blas_ex/testing_rot_batched_ex.hpp
  clients/include/blas_ex/testing_rot_ex.hpp
  clients/include/blas_ex/testing_rot_strided_batched_ex.hpp
  clients/include/blas_ex/testing_scal_batched_ex.hpp
  clients/include/blas_ex/testing_scal_ex.hpp
  clients/include/blas_ex/testing_scal_strided_batched_ex.hpp
  clients/include/hipblas_fortran.h.in
  clients/include/hipblas_fortran.hpp
  clients/include/hipblas_fortran_blas_64.f90
  clients/include/hipblas_no_fortran.hpp
  docs/functions.rst
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/hipblas_module.f90
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#824 Address CUDA CI failures
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#821 Fix hipBLAS host memory allocation
  .jenkins/common.groovy
  clients/benchmarks/CMakeLists.txt
  clients/common/host_alloc.cpp
  clients/gtest/CMakeLists.txt
  clients/gtest/blas2/gemv_gtest.yaml
  clients/gtest/hipblas_gtest_main.cpp
  clients/gtest/hipblas_test.cpp
  clients/include/d_vector.hpp
  clients/include/hipblas_init.hpp
  clients/include/hipblas_vector.hpp
  clients/include/host_alloc.hpp
  clients/include/host_batch_vector.hpp
  clients/include/utility.h
  clients/samples/example_bfdot_hip_bfloat16.cpp
  clients/samples/example_scal_ex_v2.cpp
  clients/samples/example_sscal.cpp
Labels: help wanted
