Repository ROCm/hipBLAS, pull requests merged in 2024-06, with the labels that each got.

#872 l3 64-bit interface enable
  clients/gtest/blas3/gemm_gtest.yaml
  clients/gtest/blas3/hemm_gtest.yaml
  clients/gtest/blas3/her2k_gtest.yaml
  clients/gtest/blas3/herk_gtest.yaml
  clients/gtest/blas3/herkx_gtest.yaml
  clients/gtest/blas3/symm_gtest.yaml
  clients/gtest/blas3/syr2k_gtest.yaml
  clients/gtest/blas3/syrk_gtest.yaml
  clients/gtest/blas3/syrkx_gtest.yaml
  clients/gtest/blas_ex/gemm_ex_gtest.cpp
  clients/gtest/blas_ex/gemm_ex_gtest.yaml
  clients/include/blas3/testing_hemm.hpp
  clients/include/blas3/testing_hemm_batched.hpp
  clients/include/blas3/testing_hemm_strided_batched.hpp
  clients/include/blas3/testing_herk.hpp
  clients/include/blas3/testing_herk_batched.hpp
  clients/include/blas3/testing_herk_strided_batched.hpp
  clients/include/blas3/testing_symm.hpp
  clients/include/blas3/testing_symm_batched.hpp
  clients/include/blas3/testing_symm_strided_batched.hpp
  clients/include/blas3/testing_syrk.hpp
  clients/include/blas3/testing_syrk_batched.hpp
  clients/include/blas3/testing_syrk_strided_batched.hpp
  clients/include/blas_ex/testing_gemm_batched_ex.hpp
  clients/include/blas_ex/testing_gemm_ex.hpp
  clients/include/blas_ex/testing_gemm_strided_batched_ex.hpp
  clients/include/hipblas_fortran.h.in
  clients/include/hipblas_fortran.hpp
  clients/include/hipblas_fortran_blas_64.f90
  clients/include/hipblas_no_fortran.hpp
  docs/functions.rst
  library/include/hipblas.h
  library/src/amd_detail/hipblas.cpp
  library/src/hipblas_module.f90
  library/src/nvidia_detail/hipblas.cpp
Labels: noSolver

#877 cmake: don't set CMAKE_C_COMPILER, as hipBLAS is a CXX project
  toolchain-linux.cmake
  toolchain-windows.cmake
Labels: noSolver, ci:static-libraries

#878 Fixes for static build
  CMakeLists.txt
  install.sh
Labels: noSolver, ci:static-libraries

#875 Fix rotm_strided_batched CI failures
  clients/include/blas1/testing_rotm_batched.hpp
  clients/include/blas1/testing_rotm_strided_batched.hpp
  clients/include/hipblas_init.hpp
Labels: noSolver

#880 Merge release-staging 6.2 back into develop
  CHANGELOG.md
  CMakeLists.txt
  install.sh
  toolchain-linux.cmake
  toolchain-windows.cmake
Labels: noSolver, ci:static-libraries

#882 Remove workaround for amdgpu_targets for static builds
  CMakeLists.txt
Labels: noSolver, ci:static-libraries

#885 CONTRIBUTING.md updates
  .github/CONTRIBUTING.md
  .github/CONTRIBUTING.rst
Labels: ci:docs-only
